apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedemoapp
  labels:
    app: kubedemoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedemoapp
  template:
    metadata:
      labels:
        app: kubedemoapp
    spec:
      containers:
        - name: kubedemoapp
          image: sabavathlakshmi/sample1:kubeimage1
          ports:
            - containerPort: 5000